import Carousel from '@/Components/theme_4/Common/CarouselSection'
import Header from '@/Components/theme_4/Common/Header'
import HomePage from '@/Components/theme_4/Home/Home'
import Navbar from '@/Components/theme_4/Common/NavbarPart'
import ProductTab from '@/Components/theme_4/Common/ProductTab'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '@/Components/theme_4/Common/Footer'



export default function Home() {
  return (
    <>
    <div className='ThemeFour'>
      <Head>
        <title>Theme 4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Navbar/>
        <HomePage/>
        <Footer/>

      </main>

    </div>
      
    </>
  )
}
